FROM apache/airflow:2.6.0

USER root

# Install OpenJDK and procps
RUN apt-get update && apt-get install -y openjdk-11-jdk procps && \
    rm -rf /var/lib/apt/lists/*

# Set JAVA_HOME and update PATH
ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-arm64
ENV PATH=$JAVA_HOME/bin:$PATH

USER airflow
RUN pip install apache-airflow-providers-apache-spark


